services:
  pismo-integration-service:
    build: ./
    container_name: pismo-integration-service
    restart: always
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge